apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: activemq-artemis-operator/activemq-artemis-serving-cert
  name: activemq-artemis-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: ""
    service:
      name: activemq-artemis-webhook-service
      namespace: activemq-artemis-operator
      path: /validate-broker-amq-io-v1beta1-activemqartemis
  failurePolicy: Fail
  name: vactivemqartemis.kb.io
  rules:
  - apiGroups:
    - broker.amq.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - activemqartemises
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: ""
    service:
      name: activemq-artemis-webhook-service
      namespace: activemq-artemis-operator
      path: /validate-broker-amq-io-v1beta1-activemqartemisaddress
  failurePolicy: Fail
  name: vactivemqartemisaddress.kb.io
  rules:
  - apiGroups:
    - broker.amq.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - activemqartemisaddresses
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: ""
    service:
      name: activemq-artemis-webhook-service
      namespace: activemq-artemis-operator
      path: /validate-broker-amq-io-v1beta1-activemqartemissecurity
  failurePolicy: Fail
  name: vactivemqartemissecurity.kb.io
  rules:
  - apiGroups:
    - broker.amq.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - activemqartemissecurities
  sideEffects: None
