# Note the patch file cannot be in webhook dir
# because the test will load it as a normal k8s object
# and assuming it has a metadata content!
- op: add
  path: /webhooks/0/clientConfig/caBundle
  value: ""
- op: add
  path: /webhooks/1/clientConfig/caBundle
  value: ""
- op: add
  path: /webhooks/2/clientConfig/caBundle
  value: ""
